[tool.poetry]
name = "student-project"
version = "0.1.0"
description = ""
authors = ["Dmitry Maslennikov <maslennikov.da@phystech.edu>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
uvicorn = "^0.38.0"
alembic = "^1.17.2"
sqlalchemy = "^2.0.44"
asyncpg = "^0.30.0"
fastapi = "^0.121.3"
passlib = "^1.7.4"
jose = "^1.0.0"
python-jose = "^3.5.0"
dynaconf = "^3.2.12"
pydantic = {extras = ["email"], version = "^2.12.4"}
celery = "^5.5.3"
redis = "^7.1.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
