[app_settings]
app_version = "0.1.0"
app_name = "student project"
app_host = "0.0.0.0"
app_port = 8000


[auth_settings]
sekret_key = "mipt"
algorithm = "HS256"
access_token_expire_minutes = 30

[db_settings]
db_name = "students_db"
db_user = "user"
db_password = "password"
db_host = "localhost"
db_port = 5433

[redis_settings]
redis_host = "localhost"
redis_port = 6379
broker_db = 0    # БД для брокера Celery
backend_db = 1   # БД для результатов Celery



